export const HARNESS_OWNER_TOKEN_ENV_KEY: "SUMOCODE_HARNESS_OWNER_TOKEN";
export const HARNESS_SIGNATURE_ENV_KEY: "SUMOCODE_HARNESS_SIGNATURE";
export const HARNESS_SIGNATURE: "sumocode-verification-harness-v2";
